name: zet4soft
version: "3.9"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-supersecreto}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-miapp}
      MYSQL_USER: ${MYSQL_USER:-miusuario}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-miclave}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 5001
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE:-miapp}
      DB_USER: ${MYSQL_USER:-miusuario}
      DB_PASSWORD: ${MYSQL_PASSWORD:-miclave}
    depends_on:
      db:
        condition: service_healthy
    networks: [internal, zet4soft-net]
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.yesyoucan.cat`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls.certresolver=le
      - traefik.docker.network=zet4soft-net
      - traefik.http.routers.api.service=api
      - traefik.http.services.api.loadbalancer.server.port=5001

  app:
    build:
      context: ./App
    environment:
      NODE_ENV: production
      PORT: 3001
    command: ["serve", "-s", "dist", "-l", "3001", "--single"]
    depends_on: [api]
    networks: [zet4soft-net]
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`yesyoucan.cat`) || Host(`www.yesyoucan.cat`)
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routers.app.tls.certresolver=le
      - traefik.docker.network=zet4soft-net
      - traefik.http.routers.app.service=app
      - traefik.http.services.app.loadbalancer.server.port=3001

networks:
  internal:
    name: zet4soft-internal # deja que Compose la cree (no external)
    driver: bridge
    internal: true
  zet4soft-net:
    external: true

volumes:
  db_data:
