name: zet4soft-test

services:
  test-api:
    container_name: zet4soft-api
    build:
      context: ./Api
      dockerfile: dockerfile
    image: zet4soft-api:latest
    restart: unless-stopped
    expose:
      - "5000"
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=api.zet4soft-test.com
      - LETSENCRYPT_HOST=api.zet4soft-test.com
      - VIRTUAL_PORT=5000
    networks:
      - proxy_net

  test-app:
    container_name: zet4soft-app
    build:
      context: ./App
      dockerfile: dockerfile
    image: zet4soft-app:latest
    restart: unless-stopped
    expose:
      - "3000"
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=www.zet4soft-test.com,zet4soft-test.com
      - LETSENCRYPT_HOST=www.zet4soft-test.com,zet4soft-test.com
      - VIRTUAL_PORT=3000
      - HSTS=on
    networks:
      - proxy_net

  test-db:
    container_name: zet4soft-db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - proxy_net

volumes:
  db_data:

networks:
  proxy_net:
    external: true
